server:
  port: 8888

spring:
  profile:
    active: native
  application:
    name: microservice-config
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations  #The route for all microservices will be called this--------
